// const arr = new Array("abc", "def", "ghi");
// console.log(arr);
const arr =[1,2,3,4,5];
arr.push(57);
console.log(arr);
const lastValue = arr.pop();
console.log(arr);
console.log(lastValue);
const shiftedValue = arr.shift();
console.log(arr);
console.log(shiftedValue);